src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_name__c</fullName>
        <label>Ragione sociale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Item__c.object
<CustomObject>
    <description>Elementi del piano di fatturazione dell&apos;opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Address bill to</description>
        <inlineHelpText>If this field is empty will be filled automatically with the bill to account of the opportunity</inlineHelpText>
        <label>Bill to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Items (Bill to)</relationshipLabel>
        <relationshipName>Billing_item_bill_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_with__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare il billing item correlato per fatturarli nella medesima fattura.</inlineHelpText>
        <label>Fatturare con</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 8 AND (5 OR 6 OR 7)</booleanFilter>
            <filterItems>
                <field>Billing_Item__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Bill_with__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Name</field>
                <operation>notContain</operation>
                <value>Not Touch</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoice in progress</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoiced</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_expected_date__c</field>
                <operation>equals</operation>
                <valueField>$Source.Billing_expected_date__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Item__c</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_date__c</fullName>
        <label>Data Fattura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_status__c</fullName>
        <inlineHelpText>Stato della fattura riportata automaticamente da TIC.</inlineHelpText>
        <label>Stato della Fattura</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity of the Billing Item</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TIC_draft_no__c</fullName>
        <inlineHelpText>Numero della bozza che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Bozza TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIC_invoice_no__c</fullName>
        <inlineHelpText>Numero della fattura che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Fattura TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Billing Item</label>
    <nameField>
        <label>Billing Item Name for TIC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IntegrationTIC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Impostazioni usate per l&apos;integrazione con sistema fatturazione TIC</description>
    <label>IntegrationTIC</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference billing account</description>
        <inlineHelpText>If this field is empty is filled automatically with the opportunity commercial account</inlineHelpText>
        <label>Bill to</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Bill to can be the commercial account or an account child of commercial account or the contractor account of the opportunity</errorMessage>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to)</relationshipLabel>
        <relationshipName>Opportunity_Bill_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TICApi.cls
@isTest
public class Test_TICApi {
	@TestVisible
	public static String testing;

	@TestSetup
	private static void dataFactory() {
		IntegrationTIC__c im = DataFactory.createCustomSettingsTIC();
		//List<account> Acc = DataFactory.createAccount(1, 'Luca');
		account AccPartners = DataFactory.createAccountPartners('Luca Partners');
		account AccContractor = DataFactory.createAccountContractor('Contractor');
		Opportunity Oppo = DataFactory.createOpportunity(AccPartners, AccContractor);
		Billing_Item__c BillItm = dataFactory.cretateBillingItems(Oppo, AccPartners);
	}
	
	@isTest
	private static void SendInvoice200()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Bill_with__c, TIC_draft_no__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];

		List<Id> ListIdBillItm = new List<Id> ();
		ListIdBillItm.add(BillItm[0].Id);

		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'SendToTIC';
		TICApi.sendInvoiceTIC(ListIdBillItm);
		Test.stopTest();
	}

	@isTest
	private static void SendInvoice400()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Bill_with__c, TIC_draft_no__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];

		List<Id> ListIdBillItm = new List<Id> ();
		ListIdBillItm.add(BillItm[0].Id);

		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'SendToTIC400';
		TICApi.sendInvoiceTIC(ListIdBillItm);
		Test.stopTest();
	}

	@isTest
	private static void RetrieveStatus200()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Name,Data_Ordine__c, Invoice_status__c, Account__r.Company_name__c, Bill_with__c, TIC_draft_no__c, Billing_date__c, TIC_invoice_no__c, Opportunity__r.Name, Bill_to__r.Company_name__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];
		System.debug('TIC_draft_no__c ---> ' + BillItm[0].TIC_draft_no__c);
		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'RetrieveStatusTIC';
		TICApi.retrieveStatusInvoice(BillItm);
		Test.stopTest();
	}

	@isTest
	private static void RetrieveStatus400()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Name,Data_Ordine__c, Invoice_status__c, Account__r.Company_name__c, Bill_with__c, TIC_draft_no__c, Billing_date__c, TIC_invoice_no__c, Opportunity__r.Name, Bill_to__r.Company_name__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];
		System.debug('TIC_draft_no__c ---> ' + BillItm[0].TIC_draft_no__c);
		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'RetrieveStatusTIC400';
		TICApi.retrieveStatusInvoice(BillItm);
		Test.stopTest();
	}

	@isTest
	private static void RetrieveStatusCatch()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Name,Data_Ordine__c, Invoice_status__c, Account__r.Company_name__c, Bill_with__c, TIC_draft_no__c, Billing_date__c, TIC_invoice_no__c, Opportunity__r.Name, Bill_to__r.Company_name__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];
		System.debug('TIC_draft_no__c ---> ' + BillItm[0].TIC_draft_no__c);
		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'RetrieveStatusTIC';
		TICApi.retrieveStatusInvoice(null);
		Test.stopTest();
	}

	@isTest
	private static void RetrieveStatusNumFatt()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Name, Data_Ordine__c,Invoice_status__c, Account__r.Company_name__c, Bill_with__c, TIC_draft_no__c, Billing_date__c, TIC_invoice_no__c, Opportunity__r.Name, Bill_to__r.Company_name__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];
		BillItm[0].TIC_invoice_no__c = '10/IT';
		BillItm[0].TIC_draft_no__c = '10/IT';
		update BillItm[0];
		System.debug('TIC_draft_no__c ---> ' + BillItm[0].TIC_draft_no__c);
		System.debug('TIC_invoice_no__c ---> ' + BillItm[0].TIC_invoice_no__c);
		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'RetrieveStatusTIC';
		TICApi.retrieveStatusInvoice(BillItm);
		Test.stopTest();
	}

	@isTest
	private static void generaXMLRetrieveStatusCatch()
	{
		List<Billing_Item__c> BillItm = [SELECT Id, Name,Data_Ordine__c, Invoice_status__c, Account__r.Company_name__c, Bill_with__c, TIC_draft_no__c, Billing_date__c, TIC_invoice_no__c, Opportunity__r.Name, Bill_to__r.Company_name__c FROM Billing_Item__c WHERE Name = 'test riga 1' LIMIT 1];

		System.debug('TIC_draft_no__c ---> ' + BillItm[0].TIC_draft_no__c);
		System.debug('TIC_invoice_no__c ---> ' + BillItm[0].TIC_invoice_no__c);
		Test.startTest();
		test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		testing = 'RetrieveStatusTIC';
		TICApiHelper.generaXMLRetrieveStatus(BillItm);
		Test.stopTest();
	}

	@isTest
	private static void testSchedule() {
		Test.startTest();

		// Schedule the test job
		String CRON_EXP = '0 0 0 3 9 ? 2042';
		String jobId = System.schedule('BatchSincroStatiInvoice', CRON_EXP, new SchedulableBatchSincroStatiInvoice());

		Test.stopTest();
	}

	@isTest
	private static void testSchedule2() {
		Test.startTest();

		// Schedule the test job
		String CRON_EXP = '0 0 0 3 9 ? 2042';
		String jobId = System.schedule('BatchSincroStatiInvoice2', CRON_EXP, new SchedulableBatchSincroStatiInvoice());

		Test.stopTest();
	}
	
	@isTest
	private static void structure()
	{
		List<TICstructure.dettaglioStatus> ListdettaglioStatus = new List<TICstructure.dettaglioStatus> ();
		TICstructure.dettaglioStatus dettaglioStatus = new TICstructure.dettaglioStatus();
		dettaglioStatus.data = '2024-05-01';
		dettaglioStatus.stato = '2024-05-01';
		dettaglioStatus.tipdoc = '2024-05-01';
		ListdettaglioStatus.add(dettaglioStatus);

		TICstructure.responseStatus responseStatus = new TICstructure.responseStatus();
		responseStatus.ragsoc = '2024-05-01';
		responseStatus.numtic = '2024-05-01';
		responseStatus.tipdoc = '2024-05-01';
		responseStatus.data = '2024-05-01';
		responseStatus.totale = 1;
		responseStatus.dettaglio = ListdettaglioStatus;

		TICstructure.Evasioni Evasioni = new TICstructure.Evasioni();

		Evasioni.numtic = '2024-05-01';
		Evasioni.stato = '2024-05-01';
		Evasioni.tipdoc = '2024-05-01';
		Evasioni.data = '2024-05-01';
		Evasioni.dataori = '2024-05-01';
		Evasioni.numticori = '2024-05-01';
		Evasioni.tipdocori = '2024-05-01';

		TICstructure.responseSendTIC responseSendTIC = new TICstructure.responseSendTIC();
		responseSendTIC.ragsoc = '2024-05-01';
		responseSendTIC.numtic = '2024-05-01';
		responseSendTIC.data = '2024-05-01';
		responseSendTIC.totale = 200;
		responseSendTIC.dettaglio = '2024-05-01';
		responseSendTIC.num = '2024-05-01';


		TICstructure.Documento Documento = new TICstructure.Documento();
		Documento.numero = 'a';
		Documento.cognome = 'a';
		Documento.nome = 'a';
		Documento.codicefiscale = 'a';
		Documento.numerocivico = 'a';
		Documento.email = 'a';
		Documento.stato = 'a';
		Documento.prezzoLordo = 200;
	}
	
	//commit 


}