src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_name__c</fullName>
        <label>Ragione sociale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Item__c.object
<CustomObject>
    <description>Elementi del piano di fatturazione dell&apos;opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Address bill to</description>
        <inlineHelpText>If this field is empty will be filled automatically with the bill to account of the opportunity</inlineHelpText>
        <label>Bill to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Items (Bill to)</relationshipLabel>
        <relationshipName>Billing_item_bill_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_with__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare il billing item correlato per fatturarli nella medesima fattura.</inlineHelpText>
        <label>Fatturare con</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 8 AND (5 OR 6 OR 7)</booleanFilter>
            <filterItems>
                <field>Billing_Item__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Bill_with__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Name</field>
                <operation>notContain</operation>
                <value>Not Touch</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoice in progress</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoiced</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_expected_date__c</field>
                <operation>equals</operation>
                <valueField>$Source.Billing_expected_date__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Item__c</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_date__c</fullName>
        <label>Data Fattura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_status__c</fullName>
        <inlineHelpText>Stato della fattura riportata automaticamente da TIC.</inlineHelpText>
        <label>Stato della Fattura</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity of the Billing Item</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TIC_draft_no__c</fullName>
        <inlineHelpText>Numero della bozza che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Bozza TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIC_invoice_no__c</fullName>
        <inlineHelpText>Numero della fattura che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Fattura TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Billing Item</label>
    <nameField>
        <label>Billing Item Name for TIC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IntegrationTIC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Impostazioni usate per l&apos;integrazione con sistema fatturazione TIC</description>
    <fields>
        <fullName>Stati_Finali__c</fullName>
        <description>Stati finali per cui non richiedere piu gli stati</description>
        <label>Stati Finali</label>
        <type>TextArea</type>
    </fields>
    <label>IntegrationTIC</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference billing account</description>
        <inlineHelpText>If this field is empty is filled automatically with the opportunity commercial account</inlineHelpText>
        <label>Bill to</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Bill to can be the commercial account or an account child of commercial account or the contractor account of the opportunity</errorMessage>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to)</relationshipLabel>
        <relationshipName>Opportunity_Bill_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TIC_Custom_Log__c.object
<CustomObject>
    <description>Oggetto per raccogliere i log dell&apos;integrazione con TIC</description>
    <label>TIC Custom Log</label>
    <nameField>
        <label>Nome TIC Custom Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIC Custom Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchSincroStatiInvoice2.cls
global class BatchSincroStatiInvoice2 implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {

	public static List<TIC_Custom_Log__c> TICLog = new List<TIC_Custom_Log__c> ();

	/**
	 * @description gets invoked when the batch job starts
	 * @param context contains the job ID
	 * @returns the record set as a QueryLocator object that will be batched for execution
	 */
	global Database.QueryLocator start(Database.BatchableContext context) {
		IntegrationTIC__c IntegrationTIC = IntegrationTIC__c.getOrgDefaults();

		System.debug('STATI FINALI ---> ' + IntegrationTIC.Stati_Finali__c);

		return Database.getQueryLocator('SELECT Id,Name,Invoice_status__c,Account__r.Company_name__c,Bill_with__c,TIC_draft_no__c,Data_Ordine__c,Billing_date__c,TIC_invoice_no__c,Opportunity__r.Name,Bill_to__r.Company_name__c FROM Billing_Item__c WHERE TIC_draft_no__c != null and Invoice_status__c NOT IN (' + IntegrationTIC.Stati_Finali__c + ')');
	}

	/**
	 * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
	 * @param context contains the job ID
	 * @param scope contains the batch of records to process.
	 */
	global void execute(Database.BatchableContext context, List<Billing_Item__c> scope) {
		try {

			List<Billing_Item__c> listBillingItems = new List<Billing_Item__c> ();
			listBillingItems = scope;

			//ciclo ogni billing item
			for (Billing_Item__c BI : listBillingItems)
			{
				//prendo solo i billing item "padri"
				if (String.isNotBlank(BI.Bill_with__c) == false)
				{
					//chiamata al servizio per retrieve stato
					Boolean EsitoGetStatus = TICApi.retrieveStatusInvoice(listBillingItems);
				}
			}
		} catch(Exception e) {
			System.debug('CAPTION --- ' + e.getMessage());
			string NameLog = 'Batch Sincro Stati Invoice ' + String.valueOf(Datetime.now().format('dd/MM/yyyy'));string description = 'Qualcosa è andato storto (catch) la classe schedulata BatchSincroStatiInvoice. Messaggio errore ' + e.getMessage() + '\n' + 'Line: ' + e.getLineNumber();TIC_Custom_Log__c log = CustomLog.log(NameLog, description, 'Errore batch', 'BatchSincroStatiInvoice - execute');BatchSincroStatiInvoice.TICLog.add(log);
		}
	}

	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */
	global void finish(Database.BatchableContext context) {

		System.debug('Record log da scrivere --> ' + TICLog);
		insert TICLog;

	}
}