src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_name__c</fullName>
        <label>Ragione sociale</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Item__c.object
<CustomObject>
    <description>Elementi del piano di fatturazione dell&apos;opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_with__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Selezionare il billing item correlato per fatturarli nella medesima fattura.</inlineHelpText>
        <label>Fatturare con</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 8 AND (5 OR 6 OR 7)</booleanFilter>
            <filterItems>
                <field>Billing_Item__c.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Bill_with__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Name</field>
                <operation>notContain</operation>
                <value>Not Touch</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoice in progress</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_status__c</field>
                <operation>equals</operation>
                <value>Invoiced</value>
            </filterItems>
            <filterItems>
                <field>Billing_Item__c.Billing_expected_date__c</field>
                <operation>equals</operation>
                <valueField>$Source.Billing_expected_date__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Item__c</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_number__c</fullName>
        <label>Billing number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_status__c</fullName>
        <label>Billing status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be approved</fullName>
                    <default>true</default>
                    <label>To be approved</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Invoice in progress</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Not to be invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inviata_a_TIC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inviata a TIC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_status__c</fullName>
        <inlineHelpText>Stato della fattura riportata automaticamente da TIC.</inlineHelpText>
        <label>Stato della Fattura</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_update_by_TIC__c</fullName>
        <inlineHelpText>Data ultimo aggiornamento da parte di TIC.</inlineHelpText>
        <label>Ultimo aggiornamento da TIC</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity of the Billing Item</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Billing Items</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TIC_draft_no__c</fullName>
        <inlineHelpText>Numero della bozza che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Bozza TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TIC_invoice_no__c</fullName>
        <inlineHelpText>Numero della fattura che viene aggiornato automaticamente da TIC.</inlineHelpText>
        <label>Numero Fattura TIC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tecnical_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tecnical Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tic_Invoice_Created_Date__c</fullName>
        <inlineHelpText>Data riportata automaticamente da TIC.</inlineHelpText>
        <label>Data Creazione Fatt. Tic</label>
        <type>DateTime</type>
    </fields>
    <label>Billing Item</label>
    <nameField>
        <label>Billing Item Name for TIC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TIC_Custom_Log__c.object
<CustomObject>
    <description>Oggetto per raccogliere i log dell&apos;integrazione con TIC</description>
    <label>TIC Custom Log</label>
    <nameField>
        <label>Nome TIC Custom Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIC Custom Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TICApi.cls
public class TICApi {

	public static string gblReturnMessage = '';
	public static String base64DocToSend = '';
	public static String base64DocStatus = '';
	public static TICstructure.ResponseTic res = new TICstructure.ResponseTic();
	public static TICstructure.ResponseStatusTic resStatus = new TICstructure.ResponseStatusTic();

	/**
	 * @description: Invia la fattura e righe (billing items) al sistema TIC. metodo richiamato da un flusso->avrà sempre 1 id Account nella lista di input 
	 * @param mtdAccountId: lista id dei billing items retrieve
	 */
	@InvocableMethod(label = 'Send Invoice To TIC' description = 'Invio della fattura a TIC' Callout = true)
	public static List<String> sendInvoiceTIC(List<Id> mtdBillingItemId) {

		try {
			System.debug('Billing Item ID da inviare ---> ' + mtdBillingItemId);

			//retrieve dell'account, opportunita e billing items
			List<Billing_Item__c> WorkBI = TICApiHelper.retrieveData(mtdBillingItemId);

			Boolean XML = false;
			//generazione xml e decodifica
			if (WorkBI != null) { XML = TICApiHelper.generaXML(WorkBI); }

			if (XML == true) {
				//invio della bozza a TIC
				Boolean EsitoInvio = TICApiHelper.SendToTIC();
				if (EsitoInvio == true)
				{
					//aggiornamento del numero bozza ricevuto da TIC
					string NrBozzaTic = res.Envelope.Body.su_fimport_draft_ws_RunResponse.returnXYZ[0].numtic;
					System.debug('NrBozzaTic --> ' + NrBozzaTic);
					//controllo se contiene messaggio OK --> aggiorno stato billing
					System.debug(String.valueOf(res.Envelope.Body.su_fimport_draft_ws_RunResponse.returnXYZ[0].dettaglio));
					if (String.valueOf(res.Envelope.Body.su_fimport_draft_ws_RunResponse.returnXYZ[0].dettaglio).contains('OK') == true)
					{

						System.debug('Messaggio OK --> ' + String.valueOf(res.Envelope.Body.su_fimport_draft_ws_RunResponse.returnXYZ[0].dettaglio));

						List<Billing_Item__c> ListBi = new List<Billing_Item__c> ();

						for (Billing_Item__c BI : WorkBI)
						{
							System.debug('NrBozzaTic --- ' + NrBozzaTic);
							BI.TIC_draft_no__c = NrBozzaTic;
							BI.Inviata_a_TIC__c = true;
							//BI.Billing_status__c = 'Invoice in progress';
							BI.Tic_Invoice_Created_Date__c = Datetime.now();

							ListBi.add(BI);
							//Database.SaveResult[] srList = Database.update(WorkBI, false);
							//System.debug('srList --- ' + srList);
							//update WorkBI;
						}

						update ListBi;
					}


					//aggiornamento dei billing items con nr bozza ricevuto da tic
					//update WorkBI;
					gblReturnMessage += '\n' + '\n' + 'Nr. Bozza TIC: ' + NrBozzaTic;
				}
			}

			System.debug('gblReturnMessage  ----  ' + gblReturnMessage);
			return new List<String> { gblReturnMessage };

		} catch(Exception e) {
			//GestioneLog.InsertCatchLog(e);
			gblReturnMessage = 'Qualcosa è andato storto (catch). Messaggio errore ' + e.getMessage() + '\n' + 'Line: ' + e.getLineNumber();
			return new List<String> { gblReturnMessage };
		}
	}

	/*
	 * Generazione XML da inviare per lo stato e aggiornamento stato di tutti i billing padre e figli
	 */
	public static Boolean retrieveStatusInvoice(List<Billing_Item__c> WorkBI) {

		try {

			Boolean EsitoStato = false;
			string XML = null;
			//generazione xml e decodifica

			//generazione XML da passare a zucchetti per retrieve dello stato
			if (WorkBI != null) { XML = TICApiHelper.generaXMLRetrieveStatus(WorkBI); }

			//se esito generazione XML è andata bene chiamo il servizio
			if (XML != null)
			{
				EsitoStato = TICApiHelper.GetStatusFromTIC(XML);
				System.debug('Esito stato ---> ' + EsitoStato);
			}

			//se chiamata al servizio di ricezione stato è andata bene
			if (EsitoStato == true)
			{

				System.debug('WorkBI[0].TIC_draft_no__c --- ' + WorkBI[0].TIC_draft_no__c);

				//se abbiamo solo numero bozza valorizziamo il numero della fattura per usarlo poi per la retrieve dello stato
				if (String.isNotBlank(WorkBI[0].TIC_draft_no__c) == true && String.isNotBlank(WorkBI[0].TIC_invoice_no__c) == false) {

					//controllo se evasioni è presente come tag, se nullo salto aggiornamento num fatt definitivo
					TICstructure.Evasioni Evasioni = resStatus.Envelope.Body.su_fgetdett_draft_ws_RunResponse.returnXYZ[0].evasioni;
					System.debug('Evasioni --->' + Evasioni);
					if (Evasioni != null)
					{
						System.debug('Evasioni --->' + Evasioni);
						TICstructure.Evasioni EVA = Evasioni;
						System.debug('EVA --->' + EVA);
						//aggiornamento del numero bozza ricevuto da TIC
						string NrFattTic = EVA.numtic;
						string StatoTic = EVA.stato;
						id IDBilling = WorkBI[0].Id;
						List<Billing_Item__c> GetBI = [SELECT Id, Name, Tecnical_Status__c, Invoice_status__c, Account__r.Company_name__c, TIC_invoice_no__c, TIC_draft_no__c FROM Billing_Item__c WHERE id = :IDBilling or Bill_with__c = :IDBilling];

						List<TICstructure.dettaglioStatus> dettaglioStatus = resStatus.Envelope.Body.su_fgetdett_draft_ws_RunResponse.returnXYZ[0].dettaglio;

						string StatoTicDett = (dettaglioStatus[0] != null) ? dettaglioStatus[0].stato : null;

						//per tutti i billing item padri e figlio aggiorno il numero di fattura
						for (Billing_Item__c BIUpdt : GetBI)
						{
							if (StatoTic.toUpperCase() == 'CO' || StatoTicDett.toUpperCase() == 'CONSEGNATO') {
								BIUpdt.Last_update_by_TIC__c = String.valueOf(System.Datetime.now());
								BIUpdt.TIC_invoice_no__c = NrFattTic;
								BIUpdt.Billing_number__c = NrFattTic;
								BIUpdt.Invoice_status__c = StatoTic;
								BIUpdt.Tecnical_Status__c = true;
								BIUpdt.Billing_status__c = 'Invoiced';
							}
						}
						//aggiornamento dei billing items con nr bozza ricevuto da tic
						update GetBI;

						for (Billing_Item__c BIUpdt : GetBI)
						{
							BIUpdt.Tecnical_Status__c = false;
						}
						update GetBI;
					}
				}

			} else
			{
				return false;
			}

			return true;

		} catch(Exception e) {
			//GestioneLog.InsertCatchLog(e);
			gblReturnMessage = 'Qualcosa è andato storto (catch). Messaggio errore ' + e.getMessage() + '\n' + 'Line: ' + e.getLineNumber();

			string NameLog = 'Get Status ' + String.valueOf(Datetime.now().format('dd/MM/yyyy'));
			string Billing = WorkBI[0].Name + ' - ' + WorkBI[0].Opportunity__r.Name;
			string description = 'Qualcosa è andato storto (catch) per il billing items ' + Billing + ' . Messaggio errore ' + e.getMessage() + '\n' + 'Line: ' + e.getLineNumber();
			TIC_Custom_Log__c log = CustomLog.log(NameLog, description, 'Errore ricezione stato', 'TICApi - retrieveStatusInvoice');
			BatchSincroStatiInvoice.TICLog.add(log);

			return false;
		}
	}
}