src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference billing account</description>
        <inlineHelpText>If this field is empty is filled automatically with the opportunity commercial account</inlineHelpText>
        <label>Bill to</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Bill to can be the commercial account or an account child of commercial account or the contractor account of the opportunity</errorMessage>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Partner__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Bill to)</relationshipLabel>
        <relationshipName>Opportunity_Bill_to</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billin_Plan_Status__c</fullName>
        <label>Billing Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <label>Not Completed</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <label>Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Resale</fullName>
                </value>
                <value>
                    <fullName>System Integration</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Elapsed__c</fullName>
        <label>Elapsed (months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Forfait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>CDG</fullName>
                </value>
                <value>
                    <fullName>Area SAP</fullName>
                    <label>ERP</label>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <isActive>false</isActive>
                    <label>AMS (NON USARE)</label>
                </value>
                <value>
                    <fullName>Advanced Analytics</fullName>
                    <isActive>false</isActive>
                    <label>Advanced Analytics</label>
                </value>
                <value>
                    <fullName>Digital Transformation</fullName>
                    <isActive>false</isActive>
                    <label>Digital Transformation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Open_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Opportunity open date</description>
        <label>Open date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Edit Partner Contractor field when opportunity is contractually managed by a Partner company</inlineHelpText>
        <label>Contractor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected account must be a partner company</errorMessage>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities as Contractual Partner</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Offering__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adobe Analytics</fullName>
                    <label>Adobe</label>
                </value>
                <value>
                    <fullName>Board</fullName>
                </value>
                <value>
                    <fullName>Easy Fattura</fullName>
                </value>
                <value>
                    <fullName>Google Analytics</fullName>
                    <label>Google</label>
                </value>
                <value>
                    <fullName>HFM - Conso</fullName>
                </value>
                <value>
                    <fullName>IBP</fullName>
                </value>
                <value>
                    <fullName>JDA</fullName>
                </value>
                <value>
                    <fullName>Kinaxis</fullName>
                </value>
                <value>
                    <fullName>Neptune</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>SAP Business Objects</fullName>
                </value>
                <value>
                    <fullName>SAP Business One</fullName>
                </value>
                <value>
                    <fullName>SAP ECC</fullName>
                </value>
                <value>
                    <fullName>SAP RISE S/4 HANA PUBLIC</fullName>
                </value>
                <value>
                    <fullName>SAP S/4 HANA OnPrem/Private</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <label>NA/Unknown/Other/Varie</label>
                </value>
                <value>
                    <fullName>Data Studio</fullName>
                    <isActive>false</isActive>
                    <label>Data Studio</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Power BI</fullName>
                    <isActive>false</isActive>
                    <label>Power BI</label>
                </value>
                <value>
                    <fullName>Qlik Sense</fullName>
                    <isActive>false</isActive>
                    <label>Qlik Sense</label>
                </value>
                <value>
                    <fullName>SAP GROW S4HANA Cloud public edition</fullName>
                    <isActive>false</isActive>
                    <label>SAP GROW S4HANA Cloud public edition</label>
                </value>
                <value>
                    <fullName>SAP S4HANA OnPremise/RISE Cloud private edition</fullName>
                    <isActive>false</isActive>
                    <label>SAP S4HANA OnPremise/RISE Cloud private edition</label>
                </value>
                <value>
                    <fullName>Tableau</fullName>
                    <isActive>false</isActive>
                    <label>Tableau</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Varie</fullName>
                    <isActive>false</isActive>
                    <label>Varie</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quality_review_status__c</fullName>
        <description>Quality review status for the opportunity</description>
        <label>Quality review status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be completed</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Relevant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residual_Capacity_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residual Capacity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <description>Opportunity cost</description>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SUB_LOB__c</fullName>
        <label>SUB-LOB</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>MGNT Consulting</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>ERP</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>AMS (NON USARE)</fullName>
                    <isActive>false</isActive>
                    <label>AMS (NON USARE)</label>
                </value>
                <value>
                    <fullName>CDG</fullName>
                    <isActive>false</isActive>
                    <label>CDG</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR_Project_ID__c</fullName>
        <label>TR Project ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_L__c</fullName>
        <label>T&amp;L</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not included - out of pocket</fullName>
                    <default>true</default>
                    <label>Not included - out of pocket</label>
                </value>
                <value>
                    <fullName>Not Included - forfait</fullName>
                </value>
                <value>
                    <fullName>Included - forfait</fullName>
                </value>
                <value>
                    <fullName>Not included - no refound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOppoCustomIntegration.cls
@isTest
public class TestOppoCustomIntegration {

	@isTest
	private static void CreateOpportunityToCloseWon() {

		List<account> Acc = DataFactory.createAccount(1, 'Luca');
		account AccPartners = DataFactory.createAccountPartners('Luca Pa');
		DataFactory.createImTriggerOpportunity();

		System.debug(Acc);


		Opportunity NewOppo = new Opportunity();

		NewOppo.Name = 'Test Oppo';
		NewOppo.StageName = 'Closed Won';
		NewOppo.Open_date__c = Date.today();
		NewOppo.CloseDate = Date.today().addDays(1);
		NewOppo.Line_of_Business__c = 'CRM';
		NewOppo.Partner__c = AccPartners.Id;
		NewOppo.Platform__c = 'Salesforce';
		NewOppo.Amount = 21000;
		NewOppo.Revenue__c = 10;
		NewOppo.Elapsed__c = 12;
		NewOppo.T_L__c = 'Not included - out of pocket';
		NewOppo.LeadSource = 'Salesforce event';
		NewOppo.Order_Date__c = Date.today();
		NewOppo.Order_Number__c = '123';
		NewOppo.Order_Amount__c = 21000;
		NewOppo.Contract_type__c = 'Consulting';
		NewOppo.Engagement_Type__c = 'T&M';
		//NewOppo.Billin_Plan_Status__c = 'Not Completed';
		NewOppo.Bill_to__c = Acc[0].Id;
		NewOppo.TR_Project_ID__c = 'A';
		NewOppo.Quality_review_status__c = 'Not Relevant';
		NewOppo.Residual_Capacity_Created__c = false;
		NewOppo.SUB_LOB__c = 'CRM';
		NewOppo.Offering__c = 'CRM';

		test.startTest();

		insert NewOppo;

		test.stopTest();
	}

	@isTest
	private static void UpdateOpportunityToCloseWon() {

		List<account> Acc = DataFactory.createAccount(1, 'Luca');
		account AccPartners = DataFactory.createAccountPartners('Luca Partners');


		System.debug(Acc);


		Opportunity NewOppo = new Opportunity();

		NewOppo.Name = 'Test Oppo';
		NewOppo.StageName = 'Negotiation';
		NewOppo.Open_date__c = Date.today();
		NewOppo.CloseDate = Date.today().addDays(1);
		NewOppo.Line_of_Business__c = 'CRM';
		NewOppo.Partner__c = AccPartners.Id;
		NewOppo.Platform__c = 'Salesforce';
		NewOppo.Amount = 21000;
		NewOppo.Revenue__c = 100;
		NewOppo.Elapsed__c = 12;
		NewOppo.T_L__c = 'Not included - out of pocket';
		NewOppo.LeadSource = 'Salesforce event';
		NewOppo.Order_Date__c = Date.today();

		NewOppo.Contract_type__c = 'Consulting';
		NewOppo.Engagement_Type__c = 'T&M';
		//NewOppo.Billin_Plan_Status__c = 'Not Completed';
		NewOppo.Bill_to__c = Acc[0].Id;
		NewOppo.TR_Project_ID__c = 'TES_001';
		NewOppo.Quality_review_status__c = 'Not Relevant';
		NewOppo.SUB_LOB__c = 'CRM';
		NewOppo.Offering__c = 'CRM';

		insert NewOppo;

		test.startTest();
		DataFactory.createImTriggerOpportunity();

		NewOppo.Order_Number__c = '123';
		NewOppo.Elapsed__c = 12;
		NewOppo.Engagement_Type__c = 'T&M';
		NewOppo.Order_Amount__c = 21000;
		NewOppo.StageName = 'Closed Won';
		NewOppo.TR_Project_ID__c = '456';

		update NewOppo;

		test.stopTest();
	}

}